app:
    resource: @AppBundle/Controller/
    type:     annotation

logout:
    path:   /logout

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"